services:
  crystal_isles:
    image: r15ch13/arkcluster:latest
    restart: unless-stopped
    env_file: .env
    environment:
      SERVERMAP: CrystalIsles
      SESSION_NAME: "Simplandia CrystalIsles"
      QUERY_PORT: 15000
      GAME_PORT: 15002
      RCON_PORT: 15003
    ports:
      - 15000-15003/udp
    volumes:
      - ./cluster:/cluster
      - ./server_crystal-isles:/ark
    stop_grace_period: ${STOP_GRACE_PERIOD}

  valguero:
    image: r15ch13/arkcluster:latest
    restart: unless-stopped
    env_file: .env
    environment:
      SERVERMAP: Valguero
      SESSION_NAME: "Simplandia Valguero"
      QUERY_PORT: 15010
      GAME_PORT: 15012
      RCON_PORT: 15013
    ports:
      - 15010-15013/udp
    volumes:
      - ./cluster:/cluster
      - ./server_valguero:/ark
    stop_grace_period: ${STOP_GRACE_PERIOD}
