version: '3'

env:
  NAME: ark

dotenv:
  - .env

tasks:
  default:
    desc: Build and start cluster
    cmds:
      - docker compose -p $NAME up -d --build
      - task logs

  logs:
    desc: View cluster logs
    cmds:
      - docker compose -p $NAME logs --follow

  shutdown:
    desc: Shutdown cluster
    cmds:
      - docker compose -p $NAME stop

  restart:
    desc: Restart cluster
    cmds:
      - docker compose -p $NAME restart

  clean:
    desc: Shutdown and delete containers
    cmds:
      - docker compose -p $NAME down --remove-orphans

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose -p $NAME exec -- {{.CLI_ARGS}}
